### ISSUE TITLE
Build fails after import

### ISSUE THREAD

**Issue by CaptBlackTea** [agp8x/andrograph#3]
AGPBI: {"kind":"error","text":"Attribute \"color\" has already been defined","sources":[{"file":"/app/build/intermediates/res/merged/debug/values/values.xml","position":{"startLine":346}}],"original":"","tool":"AAPT"}
/app/build/intermediates/res/merged/debug/values/values.xml:347: error: Attribute "color" has already been defined

**Comment by agp8x** [comment]
Please try with latest version again and reopen here if needed.
I have included an HowTo about using the AAR with gradle in the Readme, too.
